apply plugin: 'com.android.application'
    android {
        compileSdkVersion 37
        defaultConfig {
            applicationId "uk.me.rsw.bl"
            minSdkVersion 23
            targetSdkVersion 37
            versionCode 39
            versionName "6.5.8"
            resourceConfigurations += ['en']
            vectorDrawables.useSupportLibrary = true
        }
        buildTypes {
            release {
                debuggable false
                shrinkResources true
                minifyEnabled true
            }
            debug {
                debuggable true
                shrinkResources false
                minifyEnabled false
            }
        }
        buildFeatures {
            buildConfig = true
        }
        namespace 'uk.me.rsw.bl'
    }

    dependencies {
        implementation libs.material
        implementation libs.androidx.vectordrawable
        implementation libs.androidx.appcompat
        implementation libs.androidx.cardview
        implementation libs.androidx.preference
        implementation libs.androidx.recyclerview
        implementation libs.androidx.legacy.support.v13
        implementation libs.firebase.core
        implementation libs.firebase.appindexing
        implementation libs.sqliteassethelper
        implementation libs.material.menu.toolbar
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }
}
