#!/bin/bash

# Get script directory, and cd to it
SOURCE="${BASH_SOURCE[0]}"
while [ -h "$SOURCE" ] ; do SOURCE="$(readlink "$SOURCE")"; done
d="$( cd -P "$( dirname "$SOURCE" )" && pwd )"
cd "$d" || exit


# Create methods database
rm -f "$d/methods.db.gz"

curl "https://rsw.me.uk/blueline/data/methods.csv" > "$d/methods.csv"
sed -i "s/,t,/,1,/g; s/,f,/,0,/g" "$d/methods.csv"
sed -i "s/,t,/,1,/g; s/,f,/,0,/g" "$d/methods.csv"

line=$(head -1 "$d/methods.csv")
line=${line//stage/stage INTEGER}
line=${line//lengthofcourse/lengthofcourse INTEGER}
line=${line//numberOfHunts/numberofhunts INTEGER}
line=${line//little/little INTEGER}
line=${line//differential/differential INTEGER}
line=${line//plain/plain INTEGER}
line=${line//trebleDodging/trebledodging INTEGER}
line=${line//palindromic/palindromic INTEGER}
line=${line//doubleSym/doublesym INTEGER}
line=${line//rotational/rotational INTEGER}
line=${line//magic/magic INTEGER}

sqlite3 "$d/methods.db" <<IMPORT
CREATE TABLE methods($line);
.mode csv methods
.import methods.csv methods
DELETE FROM methods WHERE stage > 16;
UPDATE methods SET leadheadcode = 'f' WHERE leadheadcode = '0';
CREATE INDEX IF NOT EXISTS title_index ON methods (title);
CREATE INDEX IF NOT EXISTS title_magic ON methods (magic);
VACUUM;
IMPORT

gzip -9 "$d/methods.db"

rm -f "$d/methods.csv"


# Create database for user data
rm "$d/user_data.db.gz"
sqlite3 "$d/user_data.db" <<IMPORT
CREATE TABLE stars(title UNIQUE, stage INTEGER, notationExpanded, custom INTEGER);
IMPORT

gzip -9 "$d/user_data.db"
